import Link from "next/link";

export const metadata = {
  title: "Terms of Service | Flexo Africa",
  description:
    "Terms of Service governing use of the Flexo Africa customer portal.",
};

// Last updated drives the version stamp shown on-page. Bump this when the
// substantive terms change so customers can see when the policy moved.
const LAST_UPDATED = "29 June 2026";

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <p className="text-accent-500 font-semibold text-sm uppercase tracking-wider mb-3">
        Legal
      </p>
      <h1 className="text-4xl md:text-5xl font-bold text-brand-900 leading-tight">
        Terms of Service
      </h1>
      <p className="mt-4 text-brand-700">
        Last updated {LAST_UPDATED}. These terms govern your use of the Flexo
        Africa customer portal at{" "}
        <a
          href="https://portal.flexoafrica.com"
          className="text-accent-600 hover:text-accent-700"
        >
          portal.flexoafrica.com
        </a>{" "}
        and the plate brokerage services we provide. Please read them
        carefully. If anything is unclear, get in touch on{" "}
        <Link href="/contact" className="text-accent-600 hover:text-accent-700">
          our contact page
        </Link>{" "}
        before placing an order.
      </p>

      <div className="prose prose-brand mt-10 max-w-none">
        <Section title="1. Who we are">
          Flexo Africa (Pty) Ltd is a South African plate brokerage company
          based in Assagay, KwaZulu-Natal. We broker digital photopolymer
          flexographic plates across Africa and provide in-house pre-press
          repro and quality assurance. In these terms, &ldquo;we&rdquo;,
          &ldquo;us&rdquo; and &ldquo;Flexo Africa&rdquo; mean Flexo Africa
          (Pty) Ltd. &ldquo;You&rdquo; means the company or person using the
          portal.
        </Section>

        <Section title="2. Account approval">
          Signing up to the portal requires admin approval. We review every
          application within one business day. We may decline or revoke
          access at our discretion, for example where we cannot verify a
          business, where an account has been inactive for an extended
          period, or where we believe the account is being used
          inappropriately.
        </Section>

        <Section title="3. Pricing and quotes">
          Prices shown on the portal are estimates based on the dimensions,
          plate tier and turnaround you specify, plus a 4&nbsp;cm trim
          allowance added to each side of your supplied print dimensions.
          Final price is confirmed once we have reviewed your artwork. VAT
          at the current South African rate is added at checkout. Quotes
          generated by the configurator are valid for 30 days unless we
          tell you otherwise in writing.
        </Section>

        <Section title="4. Orders and payment">
          An order is placed when you confirm it through the portal. Until
          payment is received and your proof PDF is approved, the order is
          not in production. Payments are processed by PayFast (PayFast
          (Pty) Ltd) under PayFast&apos;s own terms. Where we have agreed
          credit terms with your business in writing, payment is due on
          our invoice in line with those terms. Late payments may attract
          interest at the prevailing prime rate plus 2%.
        </Section>

        <Section title="5. Artwork and proofs">
          You are responsible for the artwork you upload, including that
          you have the right to use it and that any copyright, trademark
          or brand asset is yours or licensed to you. We treat your files
          as confidential. We send a proof PDF for your approval at the
          PDF Sent stage; we cannot proceed to plating until you approve
          it. If you reject the proof we revise based on your written
          notes and resend.
        </Section>

        <Section title="6. Turnaround">
          Standard turnaround is 48 to 72 hours from file upload and proof
          approval. Express turnaround is 24 to 36 hours and carries an
          uplift. The clock starts only once both your file is uploaded
          and your proof is approved. We do our best to meet these
          windows but cannot guarantee them where third-party suppliers
          or courier networks are involved.
        </Section>

        <Section title="7. Delivery">
          Delivery is currently free of charge on all orders, by courier,
          to the address you specify at checkout. Risk passes to you on
          delivery. You may alternatively elect collection. If a delivery
          fee policy is introduced in future we will give 30 days&apos;
          notice on the portal before applying it to new orders.
        </Section>

        <Section title="8. Quality issues and returns">
          If a plate arrives with a defect that is our fault, contact us
          within 5 business days with a description and photos. We will
          remake the affected plate at no cost where the issue is
          confirmed. We do not accept returns for buyer&apos;s remorse,
          design changes after approval, or damage caused on press.
        </Section>

        <Section title="9. Confidentiality">
          We treat your files, designs, briefs and business information as
          confidential and do not share them with third parties except
          where required to fulfil your order (for example with our plate
          supplier or courier) or where required by law.
        </Section>

        <Section title="10. Liability">
          Our liability for any claim arising out of an order is limited
          to the value of that order. We are not liable for indirect or
          consequential losses, including lost profits, press downtime or
          missed marketing windows. Nothing in these terms limits
          liability that cannot be limited under South African law,
          including for death, personal injury or fraud.
        </Section>

        <Section title="11. Account suspension and termination">
          We may suspend or terminate your account if you breach these
          terms, fail to pay an invoice when due, or use the portal in a
          way that could harm Flexo Africa or other customers. You may
          close your account at any time by writing to{" "}
          <a
            href="mailto:sales@flexoafrica.com"
            className="text-accent-600 hover:text-accent-700"
          >
            sales@flexoafrica.com
          </a>
          . Closure does not affect orders already placed.
        </Section>

        <Section title="12. Changes to these terms">
          We may update these terms from time to time. The &ldquo;Last
          updated&rdquo; date at the top of the page reflects the latest
          version. For material changes we will email account holders
          before the change takes effect.
        </Section>

        <Section title="13. Governing law">
          These terms are governed by the law of the Republic of South
          Africa. Disputes that cannot be resolved by discussion are
          subject to the non-exclusive jurisdiction of the South African
          courts.
        </Section>

        <Section title="14. Contact">
          Flexo Africa (Pty) Ltd, Assagay, KwaZulu-Natal, South Africa.{" "}
          <a
            href="mailto:sales@flexoafrica.com"
            className="text-accent-600 hover:text-accent-700"
          >
            sales@flexoafrica.com
          </a>{" "}
          ·{" "}
          <a
            href="tel:+27726652041"
            className="text-accent-600 hover:text-accent-700"
          >
            +27 72 665 2041
          </a>
          .
        </Section>
      </div>

      <div className="mt-12 text-sm text-brand-600">
        See also our{" "}
        <Link
          href="/privacy"
          className="text-accent-600 hover:text-accent-700"
        >
          Privacy Policy
        </Link>
        .
      </div>
    </main>
  );
}

function Section({ title, children }) {
  return (
    <section className="mt-8">
      <h2 className="text-xl font-bold text-brand-900">{title}</h2>
      <p className="mt-2 text-brand-700 leading-relaxed">{children}</p>
    </section>
  );
}
